### PR TITLE
Custom logo feature

### PR DESCRIPTION
**Pull request by michaelO93**
Added a field for supplying custom logo

### CODE REVIEW

**Comment by bosunolanrewaju** [comment]
Nice work @michaelO93, can you squash the commits into a single commit with a descriptive message? It is good for a merge once we have the commits squashed.

**Comment by michaelO93** [comment]
Okay. How do I do that? The only commit I made was the custom logo feature. @bosunolanrewaju

**Comment by bosunolanrewaju** [comment]
@michaelO93 you have changes from @temiadesina branch I guess. Use this article to learn about **Squashing Commits:** http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by michaelO93** [comment]
@bosunolanrewaju Thanks for the article. I have squashed the commits.

**Comment by bosunolanrewaju** [comment]
@michaelO93 This branch cannot be merged as it is because it contains issues like merge conflicts and IDE generated xml files. Hence, I will be closing it and would implement the custom_logo feature in a separate branch

**Pull request closed without merging**
